using Pkg
Pkg.add("Distances")
Pkg.add("LinearAlgebra")
Pkg.add("LaTeXStrings")
Pkg.add("Random")
Pkg.add("Statistics")
Pkg.add("Plots")
Pkg.add("SpecialFunctions")
Pkg.add("QuadGK")
Pkg.add("PlotThemes")
Pkg.add("StatsBase")
Pkg.add("LsqFit")
Pkg.add("Optim")
Pkg.add("ProgressMeter")
Pkg.add("FileIO")
Pkg.add("JLD2")
Pkg.add("Dates")
